Feat [#16] 옐로하기 시작, 끝 부분 UI 구현
team-yello/YELLO-iOS pull request #20
Opened 2023-07-08 15:01 UTC by Heyjooo

## ⛏ 작업 내용

- 옐로하기_잠금 UI 구현
- 옐로하기_시작 UI 구현
- 옐로하기_포인트적립 UI 구현
- 옐로하기_투표대기 UI 구현
- 친구초대 재사용 팝업 창 UI 구현

## 📌 PR Point!

- 옐로하기_시작, 끝 부분 UI가 거의 비슷해서 재사용 뷰를 하나 만들어 사용했습니다!
- BaseViewController와 BaseView를 상속받아 구현했습니다.
- TabBarController에서 친구수가 4명 미만, 이상인 경우를 나누어 4명 미만일 때는 옐로하기_잠금 화면을, 4명 이상일 때는 옐로하기_시작 화면을 띄우도록 구현했습니다.
- 재사용 팝업창은 Inviting 폴더에 들어있습니다 ~~
- Unbounded-Bold 폰트를 추가했습니다.
- 필요한 이미지 에셋 (icClose, imgTimerBackground, imgTimerViewBackground, lbSpeechBubble) 추가했습니다.
- 현재 기기대응 관련하여 추후 수정 필요합니다 !!

## 📸 스크린샷

|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| 친구수 4명 이상일 때 |![Simulator Screen Recording - YELL O_TEST - 2023-07-08 at 23 56 48](https://github.com/team-yello/YELLO-iOS/assets/97782228/fa260fa2-7487-41c1-8eb1-c4acf2bbac58)|
| 타이머 진행 과정 |![Simulator Screen Shot - YELL O_TEST - 2023-07-08 at 21 37 11](https://github.com/team-yello/YELLO-iOS/assets/97782228/a0b8a883-3b4d-410c-af62-a2bbc9744861)|
| 친구수 4명 미만일 때 |![Simulator Screen Recording - YELL O_TEST - 2023-07-08 at 23 53 50](https://github.com/team-yello/YELLO-iOS/assets/97782228/8206517d-08e1-4ab2-b191-27469a7d8e9d)|

### ✅ Issue

Resolved #16

2023-07-08 15:46 UTC, chaentopia requested changes
고생하셨습니다~!

2023-07-08 15:46 UTC, chaentopia commented on YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingViewController.swift
> +            $0.width.equalTo(300)
**P2** 
.adjusted가 안 붙은 것 같아요! 확인 부탁드립니당~!

2023-07-08 15:46 UTC, chaentopia commented on YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingViewController.swift
> +        guard let filteredStr = originView.recommenderID.text else { return }
**P2**
약어 Str 대신 String으로 작성해주시면 감사하겠습니다!

2023-07-08 15:46 UTC, chaentopia commented on YELLO-iOS/YELLO-iOS/Presentation/Voting/BaseVotingView.swift
> +            $0.setTitle("  2900", for: .normal)
혹시 앞에 공백은 왜 들어간 걸까요!?

2023-07-08 15:46 UTC, chaentopia commented on YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerView.swift
> +    func setUI() {
**P1**
private 붙여주세요!

2023-07-08 19:20 UTC, Zoe0929 reviewed
고생하셨습니다!

2023-07-08 19:20 UTC, Zoe0929 commented on YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingViewController.swift
> +    // MARK: - copyButton 클릭했을 때
**P4** 
요 주석들은 MARK로 굳이 표시 안해도 될 것 같아요!

``` swift
// MARK: Objc Function
// close Button 클릭했을 때
...
// kakao Button 클릭했을 때
...
// copy Button 클릭했을 때
...
```
요런 주석 스타일은 어떨까요? [코드컨벤션의 MARK 주석 부분](https://www.notion.so/yell0/Code-Convention-e3fb634583164b3eb50c6619244e7e06?pvs=4#9cd8d417efbf4b50b0113af4a60ba7da) 참고하면 좋을 것 같아용~ 전체적으로 MARK 주석 달아주신 건 아주 좋습니다~~~

2023-07-08 19:20 UTC, Zoe0929 commented on YELLO-iOS/YELLO-iOS/Presentation/Base/BaseView.swift
> -    func setLayout() {}
**P4**
BaseView에도 이 함수 필요하지 않나요?! 혹시 지우신 이유가 있을까요?

2023-07-10 01:28 UTC, seungchan2 reviewed
고생하셨습니다 !

UI 구현을 하고 계신 것 같아서 코드리뷰를 남길 게 많이 없네요 ..!
참고만 해주세요 !

2023-07-10 01:28 UTC, seungchan2 commented on YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingView.swift
> +    let grayLabel = UILabel()
comment:

`blackLabel`, `grayLabel` 네이밍 보다는 역할에 따라 네이밍을 해보는 건 어떨까요 !?

2023-07-10 01:28 UTC, seungchan2 commented on YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift
> +        let nextViewController = InvitingViewController()
comment:

`yelloButtonClicked` 메서드 안에서만 사용하는 것이라면 
nextViewController -> viewController 로 써도 무방할 것 같네요!

2023-07-10 01:28 UTC, seungchan2 commented on YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerView.swift
> +            guard let remainingSeconds = self.remainingSeconds else { return }
comment:

remainingSeconds이 하나에서만 사용된다면 if ~ let 을 사용해도 좋을 것 같아요!

```swift
 if let remainingSeconds { // doSomething
 }
```

2023-07-10 04:11 UTC, chaentopia approved these changes

2023-07-10 04:12 UTC, Zoe0929 approved these changes
고생하셨습니다.

2023-07-10 04:27 UTC, merged